### ISSUE TITLE
X shaped trees in distance

### ISSUE THREAD

**Issue by lukewoodruff** [westonleavitt/TheOccultBugTracker#403] opened 2023-10-31 19:27 UTC
### What's your idea?

Trees that are far away are very visibly x shapes 2D images. I'm not sure what the best solution is, but just wanted to make the suggestion for the change. Perhaps LOD changes or imposter changes. Or maybe not having the sunlight effecting it causing the large contrast in the light and dark displaying the flat nature

### (Optional) Screen Recording or Screenshot

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/100382919/fbc9748e-2a30-4c5d-aebe-d91c15435194)

**Comment by westonleavitt** [comment] 2023-10-31 19:38
duplicate of #249

**Closed by westonleavitt** 2023-10-31 19:38 UTC
Labels: Suggestion
