### ISSUE TITLE
Players unable to build when part shows green

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/TheOccultBugTracker#286] opened 2023-08-28 16:44 UTC
### What happened?

After some time on the server players weren't able to build even when the foundation parts showed green. It would give the message "building part too far". I think we discussed this potentially being connected to the server/player location desync, but adding in case it's not fixed with that.

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

...

### Screen Recording or Screenshot

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/99694322/ceb647c5-f87b-4f91-bcde-52093b68f019)

**Comment by nbaggett** [comment] 2023-08-28 16:45
duplicate of #278 , closing for now

**Closed by nbaggett** 2023-08-28 16:45 UTC
Labels: bug
