### ISSUE TITLE
boots aren't skinned on third person mesh

### ISSUE THREAD

**Issue by nbaggett** [westonleavitt/TheOccultBugTracker#442] opened 2023-11-30 19:42 UTC
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/43483627/c8a3f5f9-748e-48eb-9c75-845a72bc61a5)

**Comment by westonleavitt** [comment] 2023-12-01 18:02
duplicate of #390

**Closed by westonleavitt** 2023-12-01 18:02 UTC
Labels: bug
